version: '3.8'
services:

  #Base de datos en redis
  redis:
    container_name: redis-airphm
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander-airphm
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  #Base de datos en neo4j
  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data/airphm/conf:/var/lib/neo4j/conf
      - ./data/airphm/data:/var/lib/neo4j/data
      - ./data/airphm/import:/var/lib/neo4j/import
      - ./data/airphm/logs:/var/lib/neo4j/logs
      - ./data/airphm/plugins:/var/lib/neo4j/plugins
    environment:
      # Raise memory limits
      server.memory.pagecache.size: 1G
      server.memory.heap.max_size: 1G
      # auth
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: neo4j/passw0rd

  #Base de datos en mongo
  mongo:
    # tomamos la última imagen de mongo
    image: mongo:latest
    container_name: mongo_airphm
    hostname: host-mongo

    # mapeo el puerto de mi computadora 27019 contra el 27017 (importante porque es el default de mongo)
    ports:
      - "27019:27017"
    volumes:
      - ~/apps/mongo_airphm:/data/db
      - ~/apps/mongo_airphm:/var/log/mongodb/
      - ./Docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: airphm

  #Base de datos en postgres
  db:
    image: postgres:15-alpine
    container_name: politics_sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./Docker/init_db.sh:/docker-entrypoint-initdb.d/01_init_db.sh

  #pgAdmin interfaz de la base de datos en postgres.
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_politics
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@phm.edu.ar
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
  pgadmin-data: